"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$directory\
[](bg:color_yellow fg:color_orange)\
$git_branch\
$git_status\
[](fg:color_yellow bg:color_aqua)\
$rust\
$golang\
$nodejs\
$php\
$haskell\
$python\
[](fg:color_aqua bg:color_blue)\
$docker_context\
$kubernetes\
[](fg:color_blue bg:color_bg3)\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
# style = "fg:color_fg0 bg:color_yellow"
style = "bg:color_orange fg:color_fg0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
# style = "bg:color_aqua"
style = "fg:color_fg0 bg:color_yellow"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_yellow)]($style)'

[git_status]
# style = "bg:color_aqua"
ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
style = "fg:color_fg0 bg:color_yellow"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[rust]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[golang]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[php]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[haskell]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[python]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[kubernetes]
disabled = false
symbol = "☸"
style = "bg:color_blue"
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_blue)]($style)'
# format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_blue)]($style)'
# format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

# [aws]
# disabled = false
# symbol = " "
# style = "bg:color_bg3"
# format = '[[ $symbol($profile) ](fg:color_fg0 bg:color_bg3)]($style)'
# force_display = true

# [azure]
# disabled = false
# style = "bg:color_bg3"
# format = '[[ $symbol($subscription) ](fg:color_fg0 bg:color_bg3)]($style)'

# [gcloud]
# disabled = false
# symbol = "󱇶 "
# style = "bg:color_bg3"
# format = '[ $symbol($project) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
