"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_0)\
$os\
$directory\
[](bg:color_1 fg:color_0)\
$git_branch\
$git_status\
[](fg:color_1 bg:color_2)\
$docker_context\
$kubernetes\
[](fg:color_2 bg:color_3)\
$golang\
$haskell\
$lua\
$python\
$rust\
[](fg:color_3 bg:color_4)\
$time\
[ ](fg:color_4)\
$line_break$character"""

# [](fg:color_3 bg:#FF9900)\
# $aws\
# [](fg:#FF9900 bg:#104581)\
# $azure\
# [](fg:#104581 bg:#4285F4)\
# $gcloud\

palette = 'autumn_harvest'

[palettes.autumn_harvest]
color_fg0 = '#fbf1c7' # Light
color_fg1 = '#ede2cc' # Dark
color_0 = '#0c3547'
color_1 = '#10656d'
color_2 = '#598f91'
color_3 = '#93b071'
color_4 = '#ede2cc'
color_5 = '#edae93'
color_6 = '#dd6670'

[os]
disabled = false
style = "bg:color_0 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[directory]
style = "bg:color_0 fg:#ede2cc"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:color_fg0 bg:color_1"
format = '[[ $symbol $branch ](fg:#ede2cc bg:color_1)]($style)'

[git_status]
ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
style = "fg:color_fg0 bg:color_1"
format = '[[($all_status$ahead_behind )](fg:#ede2cc bg:color_1)]($style)'

[kubernetes]
disabled = false
symbol = "☸"
style = "bg:color_2"
format = '[[ $symbol( $context) ](fg:color_fg1 bg:color_2)]($style)'

[docker_context]
symbol = ""
style = "bg:color_2"
format = '[[ $symbol( $context) ](fg:color_fg1 bg:color_2)]($style)'

[golang]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol( $version) ](fg:#0c3547 bg:color_3)]($style)'

[haskell]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol( $version) ](fg:#0c3547 bg:color_3)]($style)'

[lua]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol( $version) ](fg:#0c3547 bg:color_3)]($style)'

[python]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol( $version) ](fg:#0c3547 bg:color_3)]($style)'

[rust]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol( $version) ](fg:#0c3547 bg:color_3)]($style)'

# [aws]
# disabled = false
# symbol = " "
# style = "bg:#FF9900"
# format = '[[ $symbol($profile) ](fg:#252F3E bg:#FF9900)]($style)'

# [azure]
# disabled = false
# style = "bg:#104581"
# format = '[[ $symbol($subscription) ](fg:color_fg0 bg:#104581)]($style)'

# [gcloud]
# disabled = false
# symbol = "󱇶 "
# style = "bg:#4285F4"
# format = '[ $symbol($project) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_4"
format = '[[  $time ](fg:#0c3547 bg:color_4)]($style)'

[line_break]
disabled = false

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'
vimcmd_symbol = '[](bold green)'
vimcmd_replace_one_symbol = '[](bold purple)'
vimcmd_replace_symbol = '[](bold purple)'
vimcmd_visual_symbol = '[](bold yellow)'
disabled = false
