modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["WORK", "DEV", "WEB", "CHAT", "MINE"]
layouts = [
  "MainAndVertStack",
  "MainAndHorizontalStack",
  "MainAndDeck",
  "GridHorizontal",
  "EvenHorizontal",
  "EvenVertical",
  "Fibonacci",
  "CenterMain",
  "CenterMainBalanced",
  "Monocle",
  "RightWiderLeftStack",
  "LeftWiderRightStack",
]
disable_current_tag_swap = false

###### LeftWM commands
[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "HardReload"
modifier = ["modkey", "Control"]
key = "r"

[[keybind]]
command = "Execute"
value = "pkill leftwm"
modifier = ["modkey", "Shift"]
key = "x"

###### Programs shortcuts
[[keybind]]
command = "Execute"
value = "slock"
modifier = ["modkey", "Control"]
key = "l"

[[keybind]]
command = "Execute"
value = "dmenu_run"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "Execute"
value = "rofi -no-config -no-lazy-grab -show drun -modi drun -theme ~/.config/leftwm/themes/wokovo/scripts/rofi/launcher.rasi"
modifier = ["modkey"]
key = "r"

[[keybind]]
command = "Execute"
value = "splatmoji copypaste"
modifier = ["modkey"]
key = "period"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey"]
key = "Return"

##### Printscreening
[[keybind]]
command = "Execute"
value = "maim -u ~/Pictures/screenshot/screen_$(date +%Y-%m-%d-%T).png"
modifier = ["modkey"]
key = "Print"

[[keybind]]
command = "Execute"
value = "maim -s ~/Pictures/screenshot/area_$(date +%Y-%m-%d-%T).png"
modifier = ["modkey", "Shift"]
key = "Print"

[[keybind]]
command = "Execute"
value = "maim -u -i $(xdotool getactivewindow) ~/Pictures/screenshot/window_$(date +%Y-%m-%d-%T).png"
modifier = ["modkey", "Control"]
key = "Print"

###### Volume controls
[[keybind]]
command = "Execute"
value = "pactl set-sink-volume @DEFAULT_SINK@ +5%"
modifier = []
key = "XF86XK_AudioRaiseVolume"

[[keybind]]
command = "Execute"
value = "pactl set-sink-volume @DEFAULT_SINK@ -5%"
modifier = []
key = "XF86XK_AudioLowerVolume"

[[keybind]]
command = "Execute"
value = "pactl set-sink-mute @DEFAULT_SINK@ toggle"
modifier = []
key = "XF86XK_AudioMute"

###### Playback controls
[[keybind]]
command = "Execute"
value = "playerctl next"
modifier = []
key = "XF86XK_AudioNext"

[[keybind]]
command = "Execute"
value = "playerctl previous"
modifier = []
key = "XF86XK_AudioPrev"

[[keybind]]
command = "Execute"
value = "playerctl play-pause"
modifier = []
key = "XF86XK_AudioPlay"

###### TODO Brightness
[[keybind]]
command = "Execute"
value = "brightnessctl set +10%"
modifier = []
key = "XF86XK_MonBrightnessUp"

[[keybind]]
command = "Execute"
value = "brightnessctl set 10%-"
modifier = []
key = "XF86XK_MonBrightnessDown"

###### Window manipulation
[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey", "Control"]
key = "j"

[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey", "Control"]
key = "k"

[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "e"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "space"
